version: '3'

volumes:
  mongodb_volume:

services:
  server:
    container_name: node-digichlist-api
    restart: always
    build: .
    ports:
      - '5000:5000'
    # links:
    #   - mongo
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI="mongodb://20.0.0.100/app"
      - JWT=sometext

  # mongo:
  #   container_name: digichlist-api-mongo
  #   hostname: mongo
  #   image: mongo
  #   volumes:
  #     - mongodb_volume:/data/db
  #   restart: always
  #   ports:
  #     - "27017:27017"
